development:
  password: 0e1e27baecf993602d88ef7e8f99eb90
  theme_id: "80155017315"
  store: Yogaclicks.myshopify.com
production:
  password: 0e1e27baecf993602d88ef7e8f99eb90
  theme_id: "80155017315"
  store: Yogaclicks.myshopify.com
